name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxcb-xinerama0 \
          libxcb1 \
          libx11-xcb1 \
          libglu1-mesa \
          libxrender1 \
          libxext6 \
          libsm6 \
          libfontconfig1
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Xvfb
      run: |
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        Xvfb :99 &  # Запуск виртуального дисплея

    - name: Set environment variable for Qt offscreen mode
      run: |
        export QT_QPA_PLATFORM=offscreen
        python -m unittest tests.py
